[package]
org = "dinuka_amarasinghe"
name = "Test_Suite"
version = "0.1.0"
distribution = "2201.9.0-20240410-095500-2653a74d"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "persist.redis-native"
version = "0.1.0-SNAPSHOT"

